<a href="https://colab.research.google.com/github/alvarobuchen/alvarobuchen-DataScience-GenAI-Submissions/blob/main/Assignment_1/2_01_data_and_feature_engineering_in_pandas_COMPLETED.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![](https://drive.google.com/uc?export=view&id=1xqQczl0FG-qtNA2_WQYuWePW9oU8irqJ)

# Data and Feature Engineering
This Notebook will introduce us to preparing our datasets for data science and AI workloads. For sturctured data, this will often utilise popular Python libraries such as Pandas, which will be the focus for this Notebook.

### What is Pandas?
As Python has grown to become a popular solution for data analysis, many new tools have been introduced to support such tasks. Pandas is arguably the most popular and widely used of these, although it does have some limitations (if working with very large datasets you may want to look at Dask and/or PySpark).

First, we will import it into our session. This effectively means we have opened the library in the background, and can now use the [functions](https://github.com/MJMortensonWarwick/IB2AD0_Data_Science_GenerativeAI/blob/main/1_10_functions.ipynb) built into it. We will also import numpy - another widely used Python package for working with numerical data (the name is a portmanteau of "numerical" and "python"). By convention we import pandas as "pd" and numpy as "np". This is equivalent to giving it a variable name.

In [48]:
import pandas as pd
import numpy as np

### Testing our installation
To test everything is working we will create some fake data frame using numpy and load it into a pandas dataframe (more on these below). First we will create the random numbers:

In [49]:
x = np.random.rand(10,1)
x

array([[0.59747426],
       [0.87630519],
       [0.27253905],
       [0.16708424],
       [0.50172922],
       [0.99052186],
       [0.71530929],
       [0.03582624],
       [0.15399433],
       [0.55208204]])

The commands here have told numpy to create a set of random numbers between zero and one. The arguments we have passed, "1" and "10", tells numpy we want a 10x1 array of numbers (i.e. a table (more accurately a vector) with 10 rows and 1 column).

Next we will create a pandas dataframe using "x":

In [50]:
testdf = pd.DataFrame(x)
testdf

          0
0  0.597474
1  0.876305
2  0.272539
3  0.167084
4  0.501729
5  0.990522
6  0.715309
7  0.035826
8  0.153994
9  0.552082

We have now successfully created a pandas dataframe!

### What are Dataframes?
Pandas has a very elegant way of managing data, very much borrowed from the statistical language R, mostly based around dataframes. You can think of dataframes a bit like an Excel table with rows, columns and common operations like sum, average and so on. We can use this on top of our previous work on lists and dictionaries (etc.) more usable and malleable.

To begin with we will create a dataset - in this case a [dictionary](https://github.com/MJMortensonWarwick/IB2AD0_Data_Science_GenerativeAI/blob/main/1_05_dictionaries.ipynb).

In [51]:
orders = {'o10001':{'date':'2024/01/10', 'product':'Hoodie', 'quantity':'1'},
            'o10002':{'date':'2024/01/13', 'product':'Tote bag', 'quantity':'2'},
            'o10003':{'date':'2024/01/14', 'product':'Pencil', 'quantity':'10'},
            'o10004':{'date':'2024/01/15', 'product':'T-shirt', 'quantity':'2'}
}
orders

{'o10001': {'date': '2024/01/10', 'product': 'Hoodie', 'quantity': '1'},
 'o10002': {'date': '2024/01/13', 'product': 'Tote bag', 'quantity': '2'},
 'o10003': {'date': '2024/01/14', 'product': 'Pencil', 'quantity': '10'},
 'o10004': {'date': '2024/01/15', 'product': 'T-shirt', 'quantity': '2'}}

We can convert this to a Dataframe with great ease

In [52]:
import pandas as pd
import numpy as np

orders_df = pd.DataFrame(orders)
orders_df

              o10001      o10002      o10003      o10004
date      2024/01/10  2024/01/13  2024/01/14  2024/01/15
product       Hoodie    Tote bag      Pencil     T-shirt
quantity           1           2          10           2

We can even create such outputs from more complex dictionaries, such as a dictionary which includes a nested list:

In [53]:
customers = {'Mark':{'name':'Mark Johnson', 'open_orders':3, 'orders':['o10001', 'o10002', 'o10004']},
             'Katy':{'name':'Katy Hoad', 'open_orders':0, 'orders':[]},
             'Angela':{'name':'Angela Lorenz', 'open_orders':1, 'orders':['o10003']},
             'Bo':{'name':'Bo Kelestyn', 'open_orders':0, 'orders':[]}
}
customers

{'Mark': {'name': 'Mark Johnson',
  'open_orders': 3,
  'orders': ['o10001', 'o10002', 'o10004']},
 'Katy': {'name': 'Katy Hoad', 'open_orders': 0, 'orders': []},
 'Angela': {'name': 'Angela Lorenz', 'open_orders': 1, 'orders': ['o10003']},
 'Bo': {'name': 'Bo Kelestyn', 'open_orders': 0, 'orders': []}}

In [54]:
customers_df = pd.DataFrame(customers)
customers_df

                                 Mark       Katy         Angela           Bo
name                     Mark Johnson  Katy Hoad  Angela Lorenz  Bo Kelestyn
open_orders                         3          0              1            0
orders       [o10001, o10002, o10004]         []       [o10003]           []

Pandas dataframes can also be built from various other data structures and sources (including Excel files, CSVs, text files, databases and many more). For example, we can make our dataframe from a set of [lists](https://github.com/MJMortensonWarwick/IB2AD0_Data_Science_GenerativeAI/blob/main/1_04_lists.ipynb):

In [55]:
a = [1, 2, 3, 4]
b = ["a", "b", "c", "d"]
c = [True, False, True, False]

listdf = pd.DataFrame([a, b, c])
listdf

      0      1     2      3
0     1      2     3      4
1     a      b     c      d
2  True  False  True  False

## EXERCISE
Try building you own dataframes from a list and/or dictionary you create. What would happen if you have an item missing from one element. E.g. if "c" in the above example only had three items - True, False, True - rather than four. Test it - does the output match your expectation?

### Method 1: list of lists -> each list becomes a ROW

In [56]:
cities = ["Barcelona", "London", "Coventry", "Madrid"]
population_m = [1.6, 8.9, 0.35, 3.3]
capital = [False, True, False, True]

cities_df = pd.DataFrame([cities, population_m, capital])
cities_df

           0       1         2       3
0  Barcelona  London  Coventry  Madrid
1        1.6     8.9      0.35     3.3
2      False    True     False    True

### Method 2: dict of lists -> each list becomes a COLUMN (one row per city)

In [57]:
cities = ["Barcelona", "London", "Coventry", "Madrid"]
population_m = [1.6, 8.9, 0.35, 3.3]
capital = [False, True, False, True]

cities_df2 = pd.DataFrame({"city": cities, "population_m": population_m, "capital": capital})
cities_df2

        city  population_m  capital
0  Barcelona          1.60    False
1     London          8.90     True
2   Coventry          0.35    False
3     Madrid          3.30     True

### Test: list of lists with a missing value

In [58]:
cities = ["Barcelona", "London", "Coventry", "Madrid"]
population_m = [1.6, 8.9, 0.35, 3.3]
capital = [False, True, False]   # Madrid's value is missing

cities_missing = pd.DataFrame([cities, population_m, capital])
cities_missing

           0       1         2       3
0  Barcelona  London  Coventry  Madrid
1        1.6     8.9      0.35     3.3
2      False    True     False    None

### Test: dict of lists with a missing value

In [59]:
cities = ["Barcelona", "London", "Coventry", "Madrid"]
population_m = [1.6, 8.9, 0.35, 3.3]
capital = [False, True, False]   # Madrid's value is missing

try:
    cities_missing2 = pd.DataFrame({"city": cities, "population_m": population_m, "capital": capital})
    display(cities_missing2)
except ValueError as e:
    print("ValueError:", e)   # -> All arrays must be of the same length

ValueError: All arrays must be of the same length

### Fixes for the problems above

In [60]:
# Fix 1: swap rows and columns (.T) so each city is a row instead of a column
display(cities_df.T)

# Fix 2: mark the missing value explicitly with np.nan so all lists have the same length
capital = [False, True, False, np.nan]
display(pd.DataFrame({"city": cities, "population_m": population_m, "capital": capital}))

           0     1      2
0  Barcelona   1.6  False
1     London   8.9   True
2   Coventry  0.35  False
3     Madrid   3.3   True

        city  population_m capital
0  Barcelona          1.60   False
1     London          8.90    True
2   Coventry          0.35   False
3     Madrid          3.30     NaN

### Test: nested dict (labelled data) with a missing value

In [61]:
cities_dict = {
    "Barcelona": {"population_m": 1.6, "capital": False},
    "London": {"population_m": 8.9, "capital": True},
    "Coventry": {"population_m": 0.35, "capital": False},
    "Madrid": {"population_m": 3.3}   # no capital value
}
cities_dict_df = pd.DataFrame(cities_dict)
display(cities_dict_df)

# Fix 3: orient="index" gives one row per city
display(pd.DataFrame.from_dict(cities_dict, orient="index"))

             Barcelona London Coventry  Madrid
population_m       1.6    8.9     0.35     3.3
capital          False   True    False     NaN

           population_m capital
Barcelona          1.60   False
London             8.90    True
Coventry           0.35   False
Madrid             3.30     NaN

## Findings: missing values

**Expectation:** I expected pandas to either fill the gap with an empty value

**List of lists:** This ran without an error, and the empty spot was filled with None. Pandas treats each list as a row, so it just added a blank at the end of the short row. The downside is that the cities end up as columns instead of rows, and each column holds a mix of text, numbers and True/False values.

**Dict of lists:** This raised "ValueError: All arrays must be of the same length". Each list becomes a column, and pandas cannot tell which city is missing a value, so it shows an error instead of risking that the data is misaligned

**Nested dict:** This worked, and Madrid's "capital" shows "NaN". Because the data is labelled, pandas knows exactly which value is missing.

**Conclusion:** The result partly matches my expectation. Pandas only fills a gap when it can tell where the gap is, else an error will show. Labelled data (dicts) is safer, and missing values should be marked explicitly with "np.nan" rather than left out.